administration/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.login, name='login'),
	path('index/', views.index, name='index'),
    path('index/predaja/', views.thesis_submission, name='submission'),
    path('index/<int:thesis_id>/predaja/', views.thesis_update, name='update'),
    path('obavijesti/', views.notifications, name='notifications'),
    path('obavijesti/označi/sve/kao/pročitane/', views.notifications_mark_read, name='notifications_mark_read'),
    path('profil/<int:user_id>/', views.profile, name='profile'),
    path('prikaz/<int:thesis_id>/', views.thesis_display, name='thesis_display'),
    path('provjera/izvornosti/', views.generate_verification, name='generate_verification'),
    path('mentor/promjena/statusa/', views.mentor_status_change, name='mentor_status_change'),
    path('student/promjena/statusa/', views.student_status_change, name='student_status_change'),
    path('student/zamjena/datoteke/', views.student_document_change, name='student_document_change'),
    path('predsjednik/promjena/statusa/', views.president_status_change, name='president_status_change'),
    path('dodavanje/clanova/odbora/', views.add_comitee, name='add_comitee'),
    path('dodavanje/ocjene/rada/i/obrane/', views.add_grade, name='add_grade'),
    path('dodavanje/konacne/ocjene/', views.add_final_grade, name='add_final_grade'),

]

bachelor_master_administration/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')) ,
    path('saml2/', include('mockdjangosaml2.urls')),
    #path('saml2/', include('djangosaml2.urls')),
    path('', include('administration.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administration/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.utils import timezone
import os

class Role(models.Model):
	"""
    Pohranjuje uloge djelatnika u sustavu.
    """
	#diplomski 
	PREDSJEDNIK_POVJERENSTVA_DIPLOMSKI_STROJARSTVO = 1
	ZAMJENIK_POVJERENSTVA_DIPLOMSKI_STROJARSTVO = 2
	DJELOVODA_POVJERENSTVA_DIPLOMSKI_STROJARSTVO = 3

	PREDSJEDNIK_POVJERENSTVA_DIPLOMSKI_BRODOGRADNJA = 4  
	ZAMJENIK_POVJERENSTVA_DIPLOMSKI_BRODOGRADNJA = 5
	DJELOVODA_POVJERENSTVA_DIPLOMSKI_BRODOGRADNJA = 6

	PREDSJEDNIK_POVJERENSTVA_DIPLOMSKI_ELEKTROTEHNIKA = 7
	ZAMJENIK_POVJERENSTVA_DIPLOMSKI_ELEKTROTEHNIKA = 8
	DJELOVODA_POVJERENSTVA_DIPLOMSKI_ELEKTROTEHNIKA = 9

	PREDSJEDNIK_POVJERENSTVA_DIPLOMSKI_RACUNARSTVO = 10
	ZAMJENIK_POVJERENSTVA_DIPLOMSKI_RACUNARSTVO = 11
	DJELOVODA_POVJERENSTVA_DIPLOMSKI_RACUNARSTVO = 12

	#preddiplomski
	PREDSJEDNIK_POVJERENSTVA_PREDDIPLOMSKI_STROJARSTVO = 13
	ZAMJENIK_POVJERENSTVA_PREDDIPLOMSKI_STROJARSTVO = 14
	DJELOVODA_POVJERENSTVA_PREDDIPLOMSKI_STROJARSTVO = 15

	PREDSJEDNIK_POVJERENSTVA_PREDDIPLOMSKI_BRODOGRADNJA = 16
	ZAMJENIK_POVJERENSTVA_PREDDIPLOMSKI_BRODOGRADNJA = 17
	DJELOVODA_POVJERENSTVA_PREDDIPLOMSKI_BRODOGRADNJA = 18

	PREDSJEDNIK_POVJERENSTVA_PREDDIPLOMSKI_ELEKTROTEHNIKA = 19
	ZAMJENIK_POVJERENSTVA_PREDDIPLOMSKI_ELEKTROTEHNIKA = 20
	DJELOVODA_POVJERENSTVA_PREDDIPLOMSKI_ELEKTROTEHNIKA = 21

	PREDSJEDNIK_POVJERENSTVA_PREDDIPLOMSKI_RACUNARSTVO = 22
	ZAMJENIK_POVJERENSTVA_PREDDIPLOMSKI_RACUNARSTVO = 23
	DJELOVODA_POVJERENSTVA_PREDDIPLOMSKI_RACUNARSTVO = 24

	#strucni
	PREDSJEDNIK_POVJERENSTVA_STRUCNI_STROJARSTVO = 25
	ZAMJENIK_POVJERENSTVA_STRUCNI_STROJARSTVO = 26
	DJELOVODA_POVJERENSTVA_STRUCNI_STROJARSTVO = 27

	PREDSJEDNIK_POVJERENSTVA_STRUCNI_BRODOGRADNJA = 28
	ZAMJENIK_POVJERENSTVA_STRUCNI_BRODOGRADNJA = 29
	DJELOVODA_POVJERENSTVA_STRUCNI_BRODOGRADNJA = 30

	PREDSJEDNIK_POVJERENSTVA_STRUCNI_ELEKTROTEHNIKA = 31
	ZAMJENIK_POVJERENSTVA_STRUCNI_ELEKTROTEHNIKA = 32
	DJELOVODA_POVJERENSTVA_STRUCNI_ELEKTROTEHNIKA = 33
	MENTOR = 34
	KOMENTOR = 35
	

	ROLE_CHOICES = (

		#diplomski
	    (PREDSJEDNIK_POVJERENSTVA_DIPLOMSKI_STROJARSTVO, 'predsjednik povjerenstva za diplomske ispite - strojarstvo'),
	    (ZAMJENIK_POVJERENSTVA_DIPLOMSKI_STROJARSTVO, 'zamjenik povjerenstva za diplomske ispite - strojarstvo'),
	    (DJELOVODA_POVJERENSTVA_DIPLOMSKI_STROJARSTVO, 'djelovođa povjerenstva za diplomske ispite - strojarstvo'),

	    (PREDSJEDNIK_POVJERENSTVA_DIPLOMSKI_BRODOGRADNJA, 'predsjednik povjerenstva za diplomske ispite - brodogradnja'),
	    (ZAMJENIK_POVJERENSTVA_DIPLOMSKI_BRODOGRADNJA, 'zamjenik povjerenstva za diplomske ispite - brodogradnja'),
	    (DJELOVODA_POVJERENSTVA_DIPLOMSKI_BRODOGRADNJA, 'djelovođa povjerenstva za diplomske ispite - brodogradnja'),

	    (PREDSJEDNIK_POVJERENSTVA_DIPLOMSKI_ELEKTROTEHNIKA, 'predsjednik povjerenstva za diplomske ispite - elektrotehnika'),
	    (ZAMJENIK_POVJERENSTVA_DIPLOMSKI_ELEKTROTEHNIKA, 'zamjenik povjerenstva za diplomske ispite - elektrotehnika'),
	    (DJELOVODA_POVJERENSTVA_DIPLOMSKI_ELEKTROTEHNIKA, 'djelovođa povjerenstva za diplomske ispite - elektrotehnika'),

	    (PREDSJEDNIK_POVJERENSTVA_DIPLOMSKI_RACUNARSTVO, 'predsjednik povjerenstva za diplomske ispite - računarstvo'),
	    (ZAMJENIK_POVJERENSTVA_DIPLOMSKI_RACUNARSTVO, 'zamjenik povjerenstva za diplomske ispite - računarstvo'),
	    (DJELOVODA_POVJERENSTVA_DIPLOMSKI_RACUNARSTVO, 'djelovođa povjerenstva za diplomske ispite - računarstvo'),

	    #preddiplomski
	    (PREDSJEDNIK_POVJERENSTVA_PREDDIPLOMSKI_STROJARSTVO, 'predsjednik povjerenstva za završne ispite - strojarstvo sveučilišni'),
	    (ZAMJENIK_POVJERENSTVA_PREDDIPLOMSKI_STROJARSTVO, 'zamjenik povjerenstva za završne ispite - strojarstvo sveučilišni'),
	    (DJELOVODA_POVJERENSTVA_PREDDIPLOMSKI_STROJARSTVO, 'djelovođa povjerenstva za završne ispite - strojarstvo sveučilišni'),

	    (PREDSJEDNIK_POVJERENSTVA_PREDDIPLOMSKI_BRODOGRADNJA, 'predsjednik povjerenstva za završne ispite - brodogradnja sveučilišni'),
	    (ZAMJENIK_POVJERENSTVA_PREDDIPLOMSKI_BRODOGRADNJA, 'zamjenik povjerenstva za završne ispite - brodogradnja sveučilišni'),
	    (DJELOVODA_POVJERENSTVA_PREDDIPLOMSKI_BRODOGRADNJA, 'djelovođa povjerenstva za završne ispite - brodogradnja sveučilišni'),

	    (PREDSJEDNIK_POVJERENSTVA_PREDDIPLOMSKI_ELEKTROTEHNIKA, 'predsjednik povjerenstva za završne ispite - elektrotehnika sveučilišni'),
	    (ZAMJENIK_POVJERENSTVA_PREDDIPLOMSKI_ELEKTROTEHNIKA, 'zamjenik povjerenstva za završne ispite - elektrotehnika sveučilišni'),
	    (DJELOVODA_POVJERENSTVA_PREDDIPLOMSKI_ELEKTROTEHNIKA, 'djelovođa povjerenstva za završne ispite - elektrotehnika sveučilišni'),

	    (PREDSJEDNIK_POVJERENSTVA_PREDDIPLOMSKI_RACUNARSTVO, 'predsjednik povjerenstva za završne ispite - računarstvo sveučilišni'),
	    (ZAMJENIK_POVJERENSTVA_PREDDIPLOMSKI_RACUNARSTVO, 'zamjenik povjerenstva za završne ispite - računarstvo sveučilišni'),
	    (DJELOVODA_POVJERENSTVA_PREDDIPLOMSKI_RACUNARSTVO, 'djelovođa povjerenstva za završne ispite - računarstvo sveučilišni'),

	    #strucni
	    (PREDSJEDNIK_POVJERENSTVA_STRUCNI_STROJARSTVO, 'predsjednik povjerenstva za završne ispite - strojarstvo stručni'),
	    (ZAMJENIK_POVJERENSTVA_STRUCNI_STROJARSTVO, 'zamjenik povjerenstva za završne ispite - strojarstvo stručni'),
	    (DJELOVODA_POVJERENSTVA_STRUCNI_STROJARSTVO, 'djelovođa povjerenstva za završne ispite - strojarstvo stručni'),

	    (PREDSJEDNIK_POVJERENSTVA_STRUCNI_BRODOGRADNJA, 'predsjednik povjerenstva za završne ispite - brodogradnja stručni'),
	    (ZAMJENIK_POVJERENSTVA_STRUCNI_BRODOGRADNJA, 'zamjenik povjerenstva za završne ispite - brodogradnja stručni'),
	    (DJELOVODA_POVJERENSTVA_STRUCNI_BRODOGRADNJA, 'djelovođa povjerenstva za završne ispite - brodogradnja stručni'),

	    (PREDSJEDNIK_POVJERENSTVA_STRUCNI_ELEKTROTEHNIKA, 'predsjednik povjerenstva za završne ispite - elektrotehnika stručni'),
	    (ZAMJENIK_POVJERENSTVA_STRUCNI_ELEKTROTEHNIKA, 'zamjenik povjerenstva za završne ispite - elektrotehnika stručni'),
	    (DJELOVODA_POVJERENSTVA_STRUCNI_ELEKTROTEHNIKA, 'djelovođa povjerenstva za završne ispite - elektrotehnika stručni'),
	    (MENTOR, 'mentor'),
	    (KOMENTOR, 'komentor'),

	)


	id = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, primary_key=True)

	def __str__(self):
		"""
		Prikazuje ulogu u bazi u obliku stringa kao naziv uloge.
		"""
		return self.get_id_display()

	class Meta:
		db_table = 'ULOGA'
		verbose_name_plural = "ULOGE"

class Student(models.Model):
	"""
    Pohranjuje studente u sustavu,
    u relaciji sa :model:`auth.User`.
    """ 
	user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Korisnik')
	area_of_study = models.CharField(max_length=50, verbose_name='podrucjeZnanosti')
	category = models.CharField(max_length=50, verbose_name='vrstaStudenta')
	jmbag = models.CharField(max_length=50)

	def __str__ (self):
		"""
		Prikazuje studenta u bazi u obliku stringa kao ime i prezime studenta.
		"""
		return self.user.first_name + " " + self.user.last_name

	class Meta:
		db_table = 'STUDENT'
		verbose_name_plural = "STUDENTI"

class Employee(models.Model):
	"""
    Pohranjuje djelatnike u sustavu,
    u relaciji sa: :model:`auth.User`, :model:`administration.Role`.
    """ 
	user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Korisnik')
	roles = models.ManyToManyField(Role, verbose_name='Uloge')

	def __str__ (self):
		"""
		Prikazuje djelatnika u bazi u obliku stringa kao ime i prezime djelatnika.
		"""
		return self.user.first_name + " " + self.user.last_name

	class Meta:
		db_table = 'DJELATNIK'
		verbose_name_plural = "DJELATNICI"

class Study(models.Model):
	"""
    Pohranjuje sve studije fakulteta u sustav.
    """ 
	#diplomski
	DIPLOMSKI_SVEUCILISNI_STROJARSTVO = 1
	DIPLOMSKI_SVEUCILISNI_BRODOGRADNJA = 2
	DIPLOMSKI_SVEUCILISNI_ELEKTROTEHNIKA = 3
	DIPLOMSKI_SVEUCILISNI_RACUNARSTVO = 4

	#preddiplomski
	PREDDIPLOMSKI_SVEUCILISNI_STROJARSTVO = 5
	PREDDIPLOMSKI_SVEUCILISNI_BRODOGRADNJA = 6
	PREDDIPLOMSKI_SVEUCILISNI_ELEKTROTEHNIKA = 7
	PREDDIPLOMSKI_SVEUCILISNI_RACUNARSTVO = 8
	
	#strucni
	STRUCNI_STROJARSTVO = 9
	STRUCNI_BRODOGRADNJA = 10
	STRUCNI_ELEKTROTEHNIKA = 11

	STUDY_CHOICES = (
		#diplomski
		(DIPLOMSKI_SVEUCILISNI_STROJARSTVO, 'Diplomski sveučilišni studij strojarstvo'),
		(DIPLOMSKI_SVEUCILISNI_BRODOGRADNJA, 'Diplomski sveučilišni studij brodogradnja'),
		(DIPLOMSKI_SVEUCILISNI_ELEKTROTEHNIKA, 'Diplomski sveučilišni studij elektrotehnika'),
		(DIPLOMSKI_SVEUCILISNI_RACUNARSTVO, 'Diplomski sveučilišni studij računarstvo'),

		#preddiplomski
		(PREDDIPLOMSKI_SVEUCILISNI_STROJARSTVO, 'Preddiplomski sveučilišni studij strojarstvo'),
		(PREDDIPLOMSKI_SVEUCILISNI_BRODOGRADNJA, 'Preddiplomski sveučilišni studij brodogradnja'),
		(PREDDIPLOMSKI_SVEUCILISNI_ELEKTROTEHNIKA, 'Preddiplomski sveučilišni studij elektrotehnika'),
		(PREDDIPLOMSKI_SVEUCILISNI_RACUNARSTVO, 'Preddiplomski sveučilišni studij računarstvo'),
		#strucni
		(STRUCNI_STROJARSTVO, 'Preddiplomski stručni studij strojarstvo'),
		(STRUCNI_BRODOGRADNJA, 'Preddiplomski stručni studij brodogradnja'),
		(STRUCNI_ELEKTROTEHNIKA, 'Preddiplomski stručni studij elektrotehnika'),
	)

	#tip završnog rada
	ZAVRSNI = 1
	DIPLOMSKI = 2

	TYPE_CHOICES = (
		(ZAVRSNI, 'ZAVRŠNI RAD'),
		(DIPLOMSKI, 'DIPLOMSKI RAD'),
	)

	id = models.PositiveSmallIntegerField(choices=STUDY_CHOICES, primary_key=True)
	type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, default=ZAVRSNI, verbose_name='tipRadaNaStudiju')

	def __str__(self):
		"""
		Prikazuje studij u bazi u obliku stringa kao ime studija.
		"""
		return self.get_id_display()

	class Meta:
		db_table = 'STUDIJ'
		verbose_name_plural = "STUDIJI"

class StudyComitee(models.Model):
	"""
    Pohranjuje povjerenstva za studije na fakultetu,
    u relaciji sa: :model:`administration.Employee`, :model:`administration.Study`.
    """ 

    #diplomski

templates/student/student_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Student Index</title>

  	<meta name="viewport" content="width=device-width, initial-scale=1"/> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>

      	$(document).ready(function(){
      		$(window).on('popstate', function() {
      			location.reload(true);
   			});
			$('select').select2({width: "100%"});

			$(".dropdown-trigger").dropdown({
		    	coverTrigger: false,
		    	constrainWidth: false
		 	});
	    	$(document).ready(function(){
    			$('.sidenav').sidenav();
  			});
		 	$('.tabs').tabs();

		 	$('.modal').modal();


		});

		$(document).on("click", ".modal-trigger", function () {
			var content = $(this).data('thesis_id');
			$('#thesis_id').val(content);
		});
       

	    function cancel() {
	       if (confirm('Jeste li sigurni da želite odustati? \n \n Podaci/promjene neće biti sačuvane!')) {
	           window.location.href = "{% url "index" %}";
	       } 
	    }
	    function confirm_submission(){
	    	if (confirm('Jeste li sigurni da želite predati rad?')) {
	           thesis_form.submit()
	       	} 
	    }

    </script>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.4/css/materialize.min.css" rel="stylesheet"/>
    <style>

    	label {
			font-size: 20px;
		}

    </style>

</head>
<body>
	<header>
	<nav>
		<div class="nav-wrapper blue">
		    <a href="{% url "index" %}" class="left brand-logo"><img src="{% static "riteh-logo2.jpg" %}" width="80%" alt="" class="circle responsive-img"></a>
			<a href="#mobile-demo" data-target="mobile-demo" class="sidenav-trigger right"><i class="material-icons">menu</i>
		    <ul id="nav-mobile" class="right hide-on-med-and-down">
		        <li><a href="{% url 'index' %}">{{ user.first_name }} {{ user.last_name }}</a></li>
		        <li><a href="{% url 'profile' user_id=user.id %}"><i class="material-icons">account_circle</i></a></li>
		        <li><a class='dropdown-trigger' href="{% url 'notifications' %}"  data-target='dropdown1'>
				    <div class="row">
					    <div class="col s1">
							<i class="material-icons white-text notif">notifications</i>
					    </div>
					    <div class="col s1">
				     		{% if notifications_unread%}					         			
					 			<span class="badge red" style="color:white;">{{notifications_unread.count}}</span>
					         {% else %}
								&nbsp;
					         {% endif %}			  					
					    </div>		
				    </div>
				</a></li>
				
				<!-- Dropdown Structure -->
				<ul id='dropdown1' class='dropdown-content'>
					{% if notifications %}
						{% for i in notifications %}	
						   	<li> <a href="{% url 'notifications' %}?id={{i.id}}" style="color:black;{% if i.status == 1 %} background-color:#ffcdd2;{% endif %}">{{i.title}} <br>
						   	<span style="color:grey">{{i.date |  date:'d.m.Y. H:j'}}</span>
							</a></li>
							
						{% endfor %}
					{% else %}
					  	<li><a style="color:black;">Nemate nijednu obavijest</li>
					{% endif %}
					<li class = "divider"></li>
					<li><a href="{% url 'notifications_mark_read' %}" style="color:#4fc3f7;">Označi sve kao pročitano <i class="material-icons">check</i></a></li>
					<li class = "divider"></li>
					<li><a href="{% url 'notifications' %}" style="color:#4fc3f7;" class="center">Prikaži sve</a></li>
				</ul>

			  	<li><a href="{% url "saml2_logout" %}"><i class="material-icons">exit_to_app</i></a></li>
			</ul>
			<ul class="sidenav" id="mobile-demo">
		      	<li><a href="{% url 'index' %}">{{ user.first_name }} {{ user.last_name }}</a></li>
		      	<li><a href="{% url 'notifications' %}"><i class="material-icons">notifications</i>
					{% if notifications_unread%}
						<span class="badge red" style="color:white;">{{notifications_unread.count}}</span>
					{% endif %}
					Obavijesti
				</a></li>
		        <li><a href="{% url 'profile' user_id=user.id%}"><i class="material-icons">account_circle</i> Profil</a></li>
		        <li><a href="{% url 'saml2_logout' %}"><i class="material-icons">exit_to_app</i>Odjava</a></li>
  			</ul>
		</div>

	</nav>
</header>
<main>
	<div class="container">
		{% block content %}
			{% if thesis %}

	    		<ul>

	    		{% for i in thesis %}

	    			<div class="col s12 m7">				
	    				<div class="card horizontal" style="background-color:#eeeeee;">

	      					<div class="card-stacked">
	        					<div class="card-content">
	          						<p><b>Naslov: </b> <a href="{% url "thesis_display" thesis_id=i.id%}">{{i.title}}</a></p>
	          						<p><b>Vrsta rada: </b> {{i.study.get_type_display}}</p>
	          						<p><b>Mentor: </b> <a href="{% url "profile" user_id=i.mentor.user.id %}">{{i.mentor}}</a></p>
	       					 	</div>
	        					<div class="card-action right-align">
	        						<b style="{% if i.status == 5 or i.status == 9%}
												color:red;
												{% elif i.status == 6 %}
													color:#ffa000 ;
												{% else %}
												color:green;

											  {% endif %}">
									{{i.get_status_display}}</b> 
	        						{% if i.status == 1%}
	        							
	  									<p><a href="{% url "update" thesis_id=i.id %}" class="btn-floating btn-large pulse blue"><i class="material-icons">  edit</i></a></p>
	            						<br>	        						
	            					{% elif i.status == 3%}
	            					<p>
							          <form id="student_change_status" action="{% url "student_status_change" %}" method="post">
							            {% csrf_token %}
							               <input type="hidden" id="id" name="id" value="{{i.id}}">
							            <a href="javascript:{}" style="color:#2196f3;" onclick="document.getElementById('student_change_status').submit(); return false;">Predaj rad predsjedniku povjerenstva</a>
							          </form>
							          </p>
			
							         {% endif %}
	        					</div>
	        				</div>
	   					</div>
	  				</div>

	    		{% endfor %}

	    		</ul>

			{% else %}
				<br>
				<div class="row">
				    <div class="col s12">
				      <div class="card horizontal">
				      	<div class="card-stacked">
				        <div class="card-content">
				          <p>Nemate spremljen 
				          {% if 'preddiplomski' in student.category%}
				          	završni
				          {% else %}
				          	diplomski
				          {% endif %}
				      	 	rad </p>
				        </div>
				        <div class="card-action">
				          <p><a href="{% url "submission" %}" class="btn-floating btn-large pulse blue"><i class="material-icons">add</i></a> <b>Dodaj rad</b></p>
				        </div>
				      </div>
				    </div>
				    </div>
				</div>

			{% endif %} 
	 	
	 	{% endblock content %}
	</div>

<!-- modal za promjenu dokumenta rada ako je status u doradi -->
<div id="document_change" class="modal modal-fixed-header">
	<nav class="blue">
		<div class="modal-header center">ISPRAVAK RADA</div>
	</nav>
	<div class="modal-content">
		<div class="container">
			<form action="{% url "student_document_change" %}" method="post" enctype= "multipart/form-data">
				{% csrf_token %}
				<label>{{change_document_form.file.label}}(pdf):
				<h6>(naziv: ime_prezime_vrsta-rada.pdf)</h6></label>
				
				{{change_document_form.file}}
				{{change_document_form.thesis_id}}
				<br><br>
				<button class="waves-effect waves-light btn-large blue right" type="submit" name="action" value="promijeni">PROMIJENI DATOTEKU RADA</button>
			<br><br>
			</form>
		<br><br>
			
		</div>	
	</div>		
</div>
</main>
       <footer class="page-footer grey darken-1">
          <div class="container">
          	Stranica fakulteta: <a style="color:#81d4fa;" href="http://www.riteh.uniri.hr/">www.riteh.uniri.hr</a>
          </div>

          <div class="footer-copyright">
            <div class="container">
            	
            © Riteh 2020.
			
            <div class="right" href="#!">Programiranje: Valentina Ecimović</div>
            
            </div>
          </div>
        </footer>
</body>
</html>

templates/student/student_thesis_submission.html
{% extends "student/student_index.html" %}

{% block content %}

	<form id="thesis_form" action="{% url "submission" %}" method="post" enctype= "multipart/form-data">
		
			
		{% block form_body %}

			
		{% include "student/thesis_form.html" %}


		{% endblock form_body %}

		
		<div class="row">
			<div class="col s4">				
				<button class="waves-effect waves-light btn-large blue" type="submit" name="action" value="Spremi">Spremi</button>
			</div>
			<div class="col s4">				
				<button class="waves-effect waves-light btn-large blue" onclick="confirm_submission()" name="action" value="Predaj">Predaj</button>
			</div>		
		</div>
		 
	</form>

{% endblock content %}

templates/student/student_update_thesis.html
{% extends "student/student_index.html" %}

{% block content %}

	<form id="thesis_form" action="{% url "update" thesis_id=thesis_id %}" method="post" enctype= "multipart/form-data">
		
			
		{% block form_body %}
		{% include "student/thesis_form.html" %}
		{% endblock form_body %}

		
		<div class="row">
			<div class="col s4">				
				<button class="waves-effect waves-light btn-large blue" type="submit" name="action" value="Spremi">Spremi</button>
			</div>
			<div class="col s4">				
				<button class="waves-effect waves-light btn-large blue" onclick="confirm_submission()" name="action" value="Predaj">Predaj</button>
			</div>		
		</div>
		 
	</form>

{% endblock content %}